parameters:
#    gestion_de_projet_admin.example.class: GestionDeProjet\AdminBundle\Example

services:
#    gestion_de_projet_admin.example:
#        class: %gestion_de_projet_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
